# Generated by Django 3.2.4 on 2021-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('p', 'plant'), ('s', 'seeds'), ('b', 'bouquet'), ('f', 'fertilizer'), ('a', 'accessories')], max_length=20),
        ),
    ]
