# Generated by Django 3.2.4 on 2021-10-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='planting',
        ),
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.TextField(default=False, max_length=10000),
        ),
        migrations.AddField(
            model_name='product',
            name='diseases',
            field=models.TextField(default=False, max_length=10000),
        ),
    ]
