# Generated by Django 3.2.4 on 2021-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211006_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diseases',
            field=models.TextField(max_length=1000),
        ),
    ]
